package com.blueair.database;

import androidx.room.migration.Migration;
import androidx.sqlite.db.SupportSQLiteDatabase;
import kotlin.Metadata;
import kotlin.jvm.internal.Intrinsics;

@Metadata(d1 = {"\u0000\u0017\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0002\n\u0000\n\u0002\u0018\u0002\n\u0000*\u0001\u0000\b\n\u0018\u00002\u00020\u0001J\u0010\u0010\u0002\u001a\u00020\u00032\u0006\u0010\u0004\u001a\u00020\u0005H\u0016¨\u0006\u0006"}, d2 = {"com/blueair/database/BlueairDatabase$Companion$MIGRATION_48_49$1", "Landroidx/room/migration/Migration;", "migrate", "", "database", "Landroidx/sqlite/db/SupportSQLiteDatabase;", "database_otherRelease"}, k = 1, mv = {2, 2, 0}, xi = 48)
/* compiled from: BlueairDatabase.kt */
public final class BlueairDatabase$Companion$MIGRATION_48_49$1 extends Migration {
    BlueairDatabase$Companion$MIGRATION_48_49$1() {
        super(48, 49);
    }

    public void migrate(SupportSQLiteDatabase supportSQLiteDatabase) {
        Intrinsics.checkNotNullParameter(supportSQLiteDatabase, "database");
        supportSQLiteDatabase.execSQL("CREATE TABLE IF NOT EXISTS `device_table_new` (`uid` TEXT NOT NULL, `name` TEXT NOT NULL, `modelName` TEXT NOT NULL, `typeIndex` INTEGER NOT NULL, `fanSpeed` INTEGER, `filterLife` INTEGER, `autoModeText` TEXT, `brightness` INTEGER, `info` TEXT, `hasFinishedOnboarding` INTEGER NOT NULL, `lastSelectedSensorType` INTEGER, `isAblDevice` INTEGER NOT NULL, `isNightModeOn` INTEGER NOT NULL, `isChildLockOn` INTEGER NOT NULL, `linkedDeviceUid` TEXT, `connectivityStatusIndex` INTEGER NOT NULL, `lastConnectivityMillis` INTEGER NOT NULL, `mac` TEXT NOT NULL, `mcuFirmware` TEXT NOT NULL, `wifiFirmware` TEXT NOT NULL, `timeZone` TEXT NOT NULL, `serial` TEXT NOT NULL, `purchaseDate` TEXT NOT NULL, `dealerName` TEXT NOT NULL, `dealerCountry` TEXT NOT NULL, `filterType` TEXT NOT NULL, `filterTrigger` TEXT NOT NULL, `pm1Ranges` TEXT NOT NULL, `pm10Ranges` TEXT NOT NULL, `pm25Ranges` TEXT NOT NULL, `vocRanges` TEXT NOT NULL, `hchoRanges` TEXT NOT NULL, `updateProgress` INTEGER NOT NULL, `isStandByOn` INTEGER NOT NULL, `isG4NightModeOn` INTEGER NOT NULL, `isGermShieldOn` INTEGER NOT NULL, `isGermShieldNightModeOn` INTEGER, `isSafetySwitchOn` INTEGER NOT NULL, `g4NightModefilterTrigger` TEXT NOT NULL, `aimInstalled` INTEGER NOT NULL, `sku` TEXT, `compatibility` TEXT, `disinfection` INTEGER, `disinfectLeftTime` INTEGER, `disinfectLeftTimeUpdateTime` INTEGER, `uuid` TEXT, `ssid` TEXT, `bssid` TEXT, `ipv4` TEXT, `ipv6` TEXT, `timeInSeconds` INTEGER, `pm1` REAL, `pm10` REAL, `pm25` REAL, `voc` REAL, `hcho` REAL, `tmp` REAL, `hum` REAL, `fan` REAL, `lat` REAL, `lng` REAL, `radius` INTEGER, `textValue` TEXT, `isEnabled` INTEGER, PRIMARY KEY(`uid`))");
        supportSQLiteDatabase.execSQL("INSERT INTO `device_table_new` (`uid`, `name`, `modelName`, `typeIndex`, `fanSpeed`, `filterLife`, `autoModeText`, `brightness`, `info`, `hasFinishedOnboarding`, `lastSelectedSensorType`, `isAblDevice`, `isNightModeOn`, `isChildLockOn`, `linkedDeviceUid`, `connectivityStatusIndex`, `lastConnectivityMillis`, `mac`, `mcuFirmware`, `wifiFirmware`, `timeZone`, `serial`, `purchaseDate`, `dealerName`, `dealerCountry`, `filterType`, `filterTrigger`, `pm1Ranges`, `pm10Ranges`, `pm25Ranges`, `vocRanges`, `hchoRanges`, `updateProgress`, `isStandByOn`, `isG4NightModeOn`, `isGermShieldOn`, `isGermShieldNightModeOn`, `isSafetySwitchOn`, `g4NightModefilterTrigger`, `aimInstalled`, `sku`, `compatibility`, `disinfection`, `disinfectLeftTime`, `disinfectLeftTimeUpdateTime`, `uuid`, `ssid`, `bssid`, `ipv4`, `ipv6`, `timeInSeconds`, `pm1`, `pm10`, `pm25`, `voc`, `hcho`, `tmp`, `hum`, `fan`, `lat`, `lng`, `radius`, `textValue`, `isEnabled`) SELECT `uid`, `name`, `modelName`, `typeIndex`, `fanSpeed`, `filterLife`, `autoModeText`, `brightness`, `info`, `hasFinishedOnboarding`, `lastSelectedSensorType`, `isAblDevice`, `isNightModeOn`, `isChildLockOn`, `linkedDeviceUid`, `connectivityStatusIndex`, `lastConnectivityMillis`, `mac`, `mcuFirmware`, `wifiFirmware`, `timeZone`, `serial`, `purchaseDate`, `dealerName`, `dealerCountry`, `filterType`, `filterTrigger`, `pm1Ranges`, `pm10Ranges`, `pm25Ranges`, `vocRanges`, `hchoRanges`, `updateProgress`, `isStandByOn`, `isG4NightModeOn`, `isGermShieldOn`, `isGermShieldNightModeOn`, `isSafetySwitchOn`, `g4NightModefilterTrigger`, `aimInstalled`, `sku`, `compatibility`, `disinfection`, `disinfectLeftTime`, `disinfectLeftTimeUpdateTime`, `uuid`, `ssid`, `bssid`, `ipv4`, `ipv6`, `timeInSeconds`, `pm1`, `pm10`, `pm25`, `voc`, `hcho`, `tmp`, `hum`, `fan`, `lat`, `lng`, `radius`, `textValue`, `isEnabled` FROM `device_table`");
        supportSQLiteDatabase.execSQL("DROP TABLE `device_table`");
        supportSQLiteDatabase.execSQL("ALTER TABLE `device_table_new` RENAME TO `device_table`");
        supportSQLiteDatabase.execSQL("DROP TABLE `tracked_location_table`");
        supportSQLiteDatabase.execSQL("CREATE TABLE IF NOT EXISTS `tracked_location_table` (`id` TEXT NOT NULL, `latitude` REAL NOT NULL, `longitude` REAL NOT NULL, `locationName` TEXT, `cityName` TEXT, `countryName` TEXT, `countryCode` TEXT, `mapType` TEXT, PRIMARY KEY(`id`))");
        supportSQLiteDatabase.execSQL("DROP TABLE `tracked_location_data_table`");
        supportSQLiteDatabase.execSQL("CREATE TABLE IF NOT EXISTS `aqi_data_table` (`trackedLocationId` TEXT NOT NULL, `datetime` INTEGER NOT NULL, `co` REAL, `no2` REAL, `o3` REAL, `pm10` REAL, `pm25` REAL, `so2` REAL, `aqi` REAL, PRIMARY KEY(`trackedLocationId`))");
    }
}
